import os

# DATA FOLDERS
DATA_EXTERNAL = r'../data/external'
DATA_INTERIM = r'../data/interim'
DATA_RAW = r'../data/raw'
REPORTS = r'../reports'
REPORTS_FIGURES = r'../reports/figures'

# CLUB EXPRESS DATA EXPORTS
ACTIVE_MEMBERS_EXTRA_CSV = r'ActiveMembersExtra.csv'
EVENT_INFORMATION_DATA_CSV = r'event_information_data.csv'
EVENTS_AND_REGISTRANTS_CSV = r'events_and_registrants.csv'

# EXTERNAL DATA SETS
DATA_SET_GENDER_BY_NAME_ZIP = r'gender+by+name.zip'
DATA_SET_GENDER_BY_NAME_MISSING_RECORDS = r'gender+by+name+missing+records.csv'
NE_50M_ADMIN_0_COUNTRIES_ZIP = r'ne_50m_admin_0_countries.zip'

# CHARTS
CHART_CLUB_MEMBER_AGE_GENDER_DISTRIBUTION = r'club-member-age-gender-distribution.png'
CHART_CLUB_MEMBER_COUNTRY_DISTRIBUTION = r'club-member-country-distribution.png'
CHART_CLUB_MEMBER_GENDER_DISTRIBUTION = r'club-member-gender-distribution.png'

# Resolved paths
ACTIVE_MEMBERS_EXTRA_RAW = os.path.join(DATA_RAW, ACTIVE_MEMBERS_EXTRA_CSV)
ACTIVE_MEMBERS_EXTRA_INTERIM = os.path.join(DATA_INTERIM, ACTIVE_MEMBERS_EXTRA_CSV)

CLUB_MEMBER_AGE_GENDER_DISTRIBUTION = os.path.join(REPORTS_FIGURES, CHART_CLUB_MEMBER_AGE_GENDER_DISTRIBUTION)
CLUB_MEMBER_COUNTRY_DISTRIBUTION = os.path.join(REPORTS_FIGURES, CHART_CLUB_MEMBER_COUNTRY_DISTRIBUTION)
CLUB_MEMBER_GENDER_DISTRIBUTION = os.path.join(REPORTS_FIGURES, CHART_CLUB_MEMBER_GENDER_DISTRIBUTION)

GENDER_BY_NAME_ZIP = os.path.join(DATA_EXTERNAL, DATA_SET_GENDER_BY_NAME_ZIP)
GENDER_BY_NAME_MISSING_RECORDS = os.path.join(DATA_EXTERNAL, DATA_SET_GENDER_BY_NAME_MISSING_RECORDS)

NE_50M_COUNTRIES_ZIP = os.path.join(DATA_EXTERNAL, NE_50M_ADMIN_0_COUNTRIES_ZIP)

# COLOURS
CANADA_RED = '#ff0000'
GENDER_BLUE = '#1f77b4'
GENDER_PINK = '#ff69b4'
USA_BLUE = '#0000ff'
