import os

# Configuration file for the project

# Locations
DATA_SETS_PATH = r'../data-sets'
DATA_SOURCE_PATH = r'../data-sources'
DATA_OUTPUT_PATH = r'../data-output-csv'
CHART_OUTPUT_PATH = r'../data-output-charts'

# Data sets
DATA_SET_GENDER_BY_NAME_ZIP = r'gender+by+name.zip'
DATA_SET_GENDER_BY_NAME_MISSING_RECORDS = r'gender+by+name+missing+records.csv'
NE_50M_ADMIN_0_COUNTRIES_ZIP = r'ne_50m_admin_0_countries.zip'

# Files
ACTIVE_MEMBERS_EXTRA = r'ActiveMembersExtra.csv'
ACTIVE_MEMBERS_EXTRA_GENDER = r'ActiveMembersExtraGender.csv'

# Charts
CHART_CLUB_MEMBER_GENDER_DISTRIBUTION = r'club-member-gender-distribution.png'
CHART_CLUB_MEMBER_AGE_GENDER_DISTRIBUTION = r'club-member-age-gender-distribution.png'
CHART_CLUB_MEMBER_COUNTRY_DISTRIBUTION = r'club-member-country-distribution.png'

# Resolved paths
ACTIVE_MEMBERS_EXTRA_SOURCE = os.path.join(DATA_SOURCE_PATH, ACTIVE_MEMBERS_EXTRA)

ACTIVE_MEMBERS_EXTRA_CLEAN = os.path.join(DATA_OUTPUT_PATH, ACTIVE_MEMBERS_EXTRA)
ACTIVE_MEMBERS_EXTRA_GENDER = os.path.join(DATA_OUTPUT_PATH, ACTIVE_MEMBERS_EXTRA_GENDER)

CLUB_MEMBER_GENDER_DISTRIBUTION = os.path.join(CHART_OUTPUT_PATH, CHART_CLUB_MEMBER_GENDER_DISTRIBUTION)
CLUB_MEMBER_AGE_GENDER_DISTRIBUTION = os.path.join(CHART_OUTPUT_PATH, CHART_CLUB_MEMBER_AGE_GENDER_DISTRIBUTION)
CLUB_MEMBER_COUNTRY_DISTRIBUTION = os.path.join(CHART_OUTPUT_PATH, CHART_CLUB_MEMBER_COUNTRY_DISTRIBUTION)

GENDER_BY_NAME_ZIP = os.path.join(DATA_SETS_PATH, DATA_SET_GENDER_BY_NAME_ZIP)
GENDER_BY_NAME_MISSING_RECORDS = os.path.join(DATA_SETS_PATH, DATA_SET_GENDER_BY_NAME_MISSING_RECORDS)

NE_50M_COUNTRIES_ZIP = os.path.join(DATA_SETS_PATH, NE_50M_ADMIN_0_COUNTRIES_ZIP)

# Colours
BLUE = '#1f77b4'
PINK = '#ff69b4'
