import os

# DATA FOLDERS
DATA_EXTERNAL = r'../data/external'
DATA_INTERIM = r'../data/interim'
DATA_RAW = r'../data/raw'
REPORTS = r'../reports'
REPORTS_FIGURES = r'../reports/figures'

# CLUB EXPRESS DATA EXPORTS
ACTIVE_MEMBERS_EXTRA_CSV = r'ActiveMembersExtra.csv'
EVENT_INFORMATION_DATA_CSV = r'event_information_data.csv'
EVENTS_AND_REGISTRANTS_CSV = r'events_and_registrants.csv'

# EXTERNAL DATA SETS
NE_50M_ADMIN_0_COUNTRIES_ZIP = r'ne_50m_admin_0_countries.zip'
NE_50M_ADMIN_1_STATES_PROVINCES_ZIP = r'ne_50m_admin_1_states_provinces.zip'
NE_50M_POPULATED_PLACES_ZIP = r'ne_50m_populated_places.zip'

# CHARTS
CHART_CLUB_MEMBER_AGE_GENDER_DISTRIBUTION = r'club-member-age-gender-distribution.png'
CHART_CLUB_MEMBER_COUNTRY_DISTRIBUTION = r'club-member-country-distribution.png'
CHART_CLUB_MEMBER_GENDER_DISTRIBUTION = r'club-member-gender-distribution.png'

# Resolved paths
ACTIVE_MEMBERS_EXTRA_RAW = os.path.join(DATA_RAW, ACTIVE_MEMBERS_EXTRA_CSV)
ACTIVE_MEMBERS_EXTRA_INTERIM = os.path.join(DATA_INTERIM, ACTIVE_MEMBERS_EXTRA_CSV)

CLUB_MEMBER_AGE_GENDER_DISTRIBUTION = os.path.join(REPORTS_FIGURES, CHART_CLUB_MEMBER_AGE_GENDER_DISTRIBUTION)
CLUB_MEMBER_COUNTRY_DISTRIBUTION = os.path.join(REPORTS_FIGURES, CHART_CLUB_MEMBER_COUNTRY_DISTRIBUTION)
CLUB_MEMBER_GENDER_DISTRIBUTION = os.path.join(REPORTS_FIGURES, CHART_CLUB_MEMBER_GENDER_DISTRIBUTION)

NE_50M_ADMIN_0_COUNTRIES = os.path.join(DATA_EXTERNAL, NE_50M_ADMIN_0_COUNTRIES_ZIP)
NE_50M_ADMIN_1_STATES_PROVINCES = os.path.join(DATA_EXTERNAL, NE_50M_ADMIN_1_STATES_PROVINCES_ZIP)
NE_50M_POPULATED_PLACES = os.path.join(DATA_EXTERNAL, NE_50M_POPULATED_PLACES_ZIP)

# Colours
CANADA_RED = '#ff0000'
GENDER_BLUE = '#1f77b4'
GENDER_PINK = '#ff69b4'
USA_BLUE = '#0000ff'
BMW_BLUE = '#0000FF'
