#!/bin/zsh

echo "Pre-commit hook is running"
exit 1

#
# This script removes metadata and outputs from cells in a notebook.
#
# The following cells must remain empty to prevent leaking sensitive information:
# - {"metadata": {}},
# - {"outputs": []},
# 
# Jupyter notebooks are JSON files:
# {
#  "cells": [
#     {
#      "cell_type": "markdown",
#      "metadata": {},
#      "source": [
#         "## This is a markdown cell"
#      ]
#     },
#     {
#      "cell_type": "code",
#      "execution_count": null,
#      "metadata": {},
#      "outputs": [],
#      "source": [
#         "# This is a code cell\n",
#         "print(\"Hello, world!\")"
#      ]
#     }
#  ],
#  "metadata": {
#     "kernelspec": {
#      "display_name": "Python 3",
#      "language": "python",
#      "name": "python3"
#     },
#     "language_info": {
#      "codemirror_mode": {
#         "name": "ipython",
#         "version": 3
#      },
#      "file_extension": ".py",
#      "mimetype": "text/x-python",
#      "name": "python",
#      "nbconvert_exporter": "python",
#      "pygments_lexer": "ipython3",
#      "version": "3.8.5"
#     }
#  },
#  "nbformat": 4,
#  "nbformat_minor": 4
# }
#
#
# Usage:
#   $ ./strip-single-notebook.sh <notebook>
if [ -z "$1" ]; then
    echo "Usage: $0 <notebook.ipynb>"
    exit 1
fi

if ! command -v jq > /dev/null 2>&1; then
    echo "Error: jq is not installed."
    exit 1
fi

notebook="$1"

jq '
    .cells |= map(
        if .cell_type == "code" then
            .outputs = [] | .metadata = {} | .execution_count = null
        else
            .
        end
    )
' "$notebook" > tmp.$$.ipynb && mv tmp.$$.ipynb "$notebook"
